#!/usr/bin/env python3
"""Assemble audit documents from retained observations, not broker simulations."""
from pathlib import Path
import json,hashlib,re
BASE=Path(__file__).resolve().parents[1]
E='frozen/MQL5/Experts/QROS_DEMO_PORTFOLIO_EXECUTOR_v2.mq5'
B='frozen/MQL5/Include/QROS_DEMO_BUS_v2.mqh'
R='frozen/MQL5/Include/QROS_RISK_KERNEL_APPROVED_v15420.mqh'
C='frozen/MQL5/Scripts/QROS_V223_RUNTIME_BOOTSTRAP.mq5'
HEAD='3c92d2ca50fb08d3b51d19f6f042f328797460e4'
BRANCH='audit/demo-forward-v2.2.3-frozen-20260907'
F=[]
def finding(id,severity,title,locations,tests,static,scenario,consequence,repair,semantic='execution-semantic',classification='STATIC_PROVEN'):
 F.append(dict(id=id,severity=severity,title=title,classification=classification,locations=[dict(file=p,function=fn,line=n) for p,fn,n in locations],test_ids=tests.split(),source_conclusion=static,deterministic_scenario=scenario,consequence=dict(classification='INFERRED',text=consequence),active_v223_exposure=dict(classification='INFERRED',code_path_present=classification!='BLOCKED',incident_observed=False,text='Expuesto si ocurre el escenario en el ejecutable vinculado a estas fuentes; no se inspeccionó el terminal ni se demuestra un incidente del forward.'),proposed_correction=repair,semantic_class=semantic))
finding('F01','Critical','Solicitudes pendientes y fills no reconciliados escapan de reservas y exclusión de activo',[(E,'ReservedRiskUsd',199),(E,'AnyPositionOnAsset',176),(E,'SendEntry',295),(E,'SendEntry',340),(E,'OnInit',467)],'T17 T18 T19 T20 T21 T22 T76 T78','Se cuentan posiciones visibles; no se enumeran órdenes ni existe registro de intención pendiente, reconciliación de transacciones, ResultVolume/ResultPrice o validación del SL/TP resultante. PLACED y DONE_PARTIAL avanzan contador/LASTEV y registran EXECUTED; timeout/rechazo no conserva reserva de incertidumbre.','Stub: balance 10000, tres intenciones de 50 USD, dos sobre NDX, con PLACED sin posición visible. Se aceptan las tres y quedan 150 USD reservados. Con medio fill visible y remanente pendiente vuelve a ocurrir. Timeout con orden viva permite otra solicitud del mismo activo.','El contrato de 1% máximo y una posición por activo no queda garantizado. Visibilidad tardía, fill real distinto o posición sin protección pueden quedar sin detección; una cancelación deja un contador inexacto. Que Darwinex produzca cada combinación debe probarse en host aislado.','Intención durable antes de enviar, reserva de riesgo/activo/cupo hasta desenlace confirmado; reconciliar órdenes, deals, posiciones, volumen y barreras. REPLACEMENT_CONTRACT puntos 1–5. La propuesta parcial NO corrige F01.')
finding('F02','High','Modify/Close confunden booleano de envío con ejecución y pierden intención de reintento',[(E,'HandleModify',358),(E,'HandleModify',372),(E,'HandleClose',376),(E,'HandleClose',385),(E,'ForceNoOvernight',410)],'T23 T24 T25 T26 T39 T77 T80','El branch EXECUTED de modify/close depende únicamente del bool. ResultRetcode sólo informa algunos fallos booleanos; no hay verificación de estado ni cola durable de cierre/modificación. ForceNoOvernight omite el retcode incluso en el texto de fallo.','Inyectar bool=true, retcode=10006 y posición intacta: se registra EXECUTED. DONE_PARTIAL con remanente abierto también. Con bool=false y posterior recuperación, sin nuevo evento del módulo no se reintenta la intención durante el mismo día.','La protección/cierre solicitado puede no aplicarse y el ledger puede afirmar éxito. El par booleano/retcode real de Trade.mqh build 6182 sigue BLOCKED; el defecto de control de flujo es verificable estáticamente.','Comprobar retcode y resultado reconciliado; persistir la intención hasta confirmación. La propuesta parcial elimina éxito falso en los casos probados; aún no añade reintento durable.')
finding('F03','Critical','g_fault persistente abandona la gestión posterior de posiciones',[(E,'SetFault',106),(E,'ArmGate',123),(E,'OnTimer',488),(E,'OnTick',499),(E,'PollBus',421)],'T27 T28 T29 T64 T87','SetFault es sticky. OnTimer publica HB/ARMED y retorna antes de ForceNoOvernight, PollBus y ProcessPending; OnTick tampoco los ejecuta con fault. El fault se activa por overflow/torn slot, riesgo desconocido o permisos temporales. Dentro del primer PollBus que falla pueden procesarse otros módulos; los ciclos posteriores quedan omitidos.','Posición QROS abierta del día anterior, SetFault por bus y OnTimer: cero intentos de cierre. Un evento CLOSE posterior no se consume. Deshabilitar temporalmente TERMINAL_TRADE_ALLOWED en HandleClose y restaurarlo deja la misma situación.','Pérdida determinista de la ruta central de gestión y del fallback diario mientras subsista la posición. SL/TP del broker, si existen, son la única protección remanente demostrable desde este núcleo. Esto basta para rechazar seguridad incondicional del runtime.','Separar bloqueo de entradas de gestión de inventario reconciliado. La propuesta conserva el cierre diario con fault, pero NO recupera gestión intradía ni procesa un bus de integridad dudosa.')
finding('F04','Critical','Recuperación no reconstruye protección/intenciones y el lock nunca se libera',[(E,'OnInit',458),(E,'OnInit',467),(E,'OnInit',475),(E,'SendEntry',302),(C,'OnStart',317)],'T30 T31 T32 T33 T34 T65 T78','OnInit detecta sólo posiciones por magic, pone g_recovery_lock=true y fija consumed=HEAD para todos los tipos de evento. No reconstruye estado del módulo ni órdenes/SL/TP; no existe asignación de liberación del lock. El bootstrap requiere cero posiciones para certificar.','Reiniciar con SL=0: init retorna éxito, lock=true y no hay reparación/close en timer del mismo día. Un CLOSE anterior al restart se descarta. Flat + CERT=1 tampoco libera lock. Control: un CLOSE nuevo sí se procesa aun con lock y CERT=0.','Una posición puede quedar sin protección o sin la gestión que existía antes del reinicio. No se afirma que toda posición protegida se abandone: cierre nuevo y fallback diario sano funcionan. La reconstrucción específica de emisores permanece BLOCKED_PENDING_EXACT_SOURCE_IMPORT.','Reconstruir inventario de órdenes/deals/posiciones y estado por generación/módulo; conservar manejo independiente durante recovery. Liberar sólo tras flat real, ausencia de órdenes, historial completo y recertificación. No parchear emisores aproximados.')
finding('F05','High','HistorySelect fallido habilita contador diario cero',[(E,'RebuildDailyCount',223),(E,'RefreshDay',257),(E,'SendEntry',308)],'T12 T35 T36 T40','g_day_entries se pone a cero antes de HistorySelect; false retorna sin fault. La reconstrucción exitosa deduplica DEAL_POSITION_ID, no intención/orden de entrada. No hay contador durable de reservas pendientes.','Con tres entradas históricas, HistorySelect=false y señal fresca, el stub acepta una cuarta entrada. Con historial completo y tres position IDs distintos, sí bloquea; fills divididos con un mismo ID cuentan una vez.','Máximo tres entradas por día deja de garantizarse durante indisponibilidad de historial/restart. Netting o múltiples entradas en un mismo POSITION_ID pueden subcontar; la forma real del historial depende de MT5/broker y sigue BLOCKED.','Fallo de historial bloquea nuevas entradas y exige reconstrucción autoritativa por intención. La propuesta agrega fault y relectura de fault tras RefreshDay; contabilidad durable pendiente.')
finding('F06','High','No overnight actúa después de medianoche y OnTick puede adelantar entradas',[(E,'ForceNoOvernight',389),(E,'ForceNoOvernight',401),(E,'OnTimer',493),(E,'OnTick',502)],'T37 T38 T39 T40 T74 T81','ForceNoOvernight sólo cierra cuando la fecha de apertura difiere de ServerDayKey actual. OnTick procesa entradas sin ForceNoOvernight. No hay deadline previo al fin de sesión ni calendario de negociación.','A las 23:59:59 la posición sigue abierta; el primer timer del día siguiente sano intenta cerrar. OnTick del día nuevo puede aceptar NDX mientras queda XAU del anterior. Rechazo/desconexión prolonga la posición.','No se garantiza el contrato literal de no cruzar el día. No se sustituye por liquidación posterior a medianoche. Un emisor podría cerrar antes: esa protección adicional queda bloqueada hasta importar sus bytes.','Vincular deadline previo a sesiones/calendario autorizado y política de contingencia; comprobarlo antes de cualquier entrada. No inventar cutoff, precio de EOF ni ejecución en mercado cerrado.')
finding('F07','High','Lector acepta payload nuevo con SEQ viejo durante sobrescritura del ring',[(B,'QrosBusPublish',101),(B,'QrosBusPublish',104),(B,'QrosBusPublish',115),(B,'QrosBusRead',127),(B,'QrosBusRead',143)],'T41 T42 T43 T44 T86','El escritor no invalida SEQ antes de modificar payload. El double-check sólo detecta cambios en SEQ; un SEQ viejo estable no acredita que el payload viejo siga intacto.','Publicar 1..32; pausar 33 tras escribir payload del slot 1 y antes de SEQ. Leer seq=1: ambas comprobaciones ven 1, pero event_ms=33. No requiere dos productores ni HEAD que ya marque overflow.','Datos de eventos distintos pueden mezclarse o aplicarse bajo identidad/orden causal incorrectos; también afecta CLOSE/SL. La triage previa sobre coherencia garantizada con un productor debe corregirse.','Invalidar/reservar slot antes de payload y usar versión/época con publicación verificada; rechazo de escritura concurrente, propiedad de productor y recuperación durable.')
finding('F08','High','Publicación y ejecución carecen de exclusión de instancia',[(B,'QrosBusPublish',101),(B,'QrosBusKey',38),(E,'OnInit',458),(C,'RuntimeFailure',234)],'T46 T47 T66 T75','HEAD+1 no usa compare-and-swap ni lease. Namespace QDB1 no incorpora cuenta/época/propietario. OnInit no verifica otro executor; bootstrap sólo verifica nombres de tres emisores en charts creados.','Dos publicaciones del mismo módulo intercaladas tras leer HEAD=0 completan con HEAD=1. Módulos diferentes mantienen cabezas independientes. Dos inicios flat pasan en el stub. Dos espacios de terminal aislados aceptan bajo snapshots de cuenta retrasados.','Pérdida de eventos o doble solicitud. T75 prueba sólo snapshots independientes; no ejecuta dos terminales reales ni afirma que compartan globales. El wrapper puede imponer exclusión externa: BLOCKED_PENDING_EXACT_SOURCE_IMPORT.','Propietario/fencing por cuenta y época, productor exclusivo por módulo. Verificar despliegue exacto; no suponer que un mutex local cubre otro terminal.')
finding('F09','High','Persistencia del bus y commits de estado no se verifican',[(B,'QrosBusPublish',104),(B,'QrosBusRead',132),(E,'PollBus',420),(E,'SendEntry',352)],'T33 T41 T45 T48 T55 T79','GlobalVariableSet se ignora en payload, SEQ, HEAD, DAY y LASTEV. No hay GlobalVariablesFlush ni protocolo durable de época/recuperación. QrosBusRead sólo exige existencia de SEQ; PollBus no detecta HEAD regresivo.','Falla escribir HEAD después de SEQ: Publish retorna true con HEAD=0 y no se consume. HEAD baja de 10 a 2: no hay fault. Borrar SL con SEQ válido: lector acepta SL=0.','Pérdida de intención, bloqueo hasta vieja cabeza o estado diario/timestamp inconsistente tras caída. Durabilidad real de globals en Windows/MT5 permanece BLOCKED; no se simula fsync ni crash real.','Comprobar escrituras, commit atómico/versionado, flush validado, snapshot y rechazo de rollback; no usar ausencia como cero autorizado.')
finding('F10','High','Buffer individual y dispatch inmediato CLOSE rompen orden causal global',[(E,'Before',275),(E,'PollBus',431),(E,'ProcessPending',439),(E,'HandleClose',378)],'T13 T14 T52 T53 T85','SortPending ordena timestamp/prioridad/perfil, pero cada entrada madura según su propio received_uptime. CLOSE/MODIFY se ejecutan durante PollBus y ENTRY se difiere. Gestión sólo se vincula por símbolo/magic.','NDX llega primero; XAU del mismo ms llega 100ms después. A +300ms XAU sigue inmaduro y NDX se envía. ENTRY luego CLOSE sin posición: close no hace nada y la entrada aparece después. Close viejo cierra nueva generación con mismo magic.','Prioridad y relación orden→posición→gestión no garantizadas fuera del lote ideal. Los emisores exactos podrían restringir secuencias, aún bloqueados.','Arbitraje por cohorte completa/watermark, identidad de intención/generación y cancelación de entradas pendientes ante close causal. Conservar orden confirmado close→entry que pasa T85.')
finding('F11','High','Sólo se deduplica último timestamp y no hay validación de edad de evento',[(E,'SendEntry',310),(E,'AddPending',269),(B,'QrosBusRead',134),(E,'RebuildDailyCount',251)],'T15 T33 T41 T49','LASTEV guarda sólo última aceptación; compara igualdad, no frontera causal ni conjunto durable. entry_ref y publish_uptime_ms se transportan pero no se validan al enviar. Skip de replay inicial se limita a HEAD existente.','Tras entradas A y B y quedar flat, volver a publicar A con secuencia nueva lo acepta. Evento del día anterior en nueva secuencia también se envía con tick actual.','Posible duplicación económica de timestamp, señal caducada y cupo atribuido al día de procesamiento. Monotonía completa debe probarse con emisores exactos.','Identidad/deduplicación durable, día/época y frontera causal por emisor; frescura autorizada sin umbrales científicos inventados.')
finding('F12','High','Reserva usa SL actual y faltan finitud/conciliación del precio efectivo',[(E,'ReservedRiskUsd',210),(E,'ReservedRiskUsd',218),(E,'SendEntry',327),(R,'QrosRiskSize',84),(R,'QrosRiskSize',122)],'T07 T08 T09 T10 T21 T67 T68 T83 T84','Reserva=abs(OrderCalcProfit(open, SL_actual, volumen)), sin riesgo inicial guardado. SL en BE da cero; SL por encima puede contar beneficio como riesgo. No se comprueba finitud de p/total. Ambas cotas monetarias admiten 0.01 USD de tolerancia.','Posición inicial de 50 USD reporta cero al mover SL a entrada. Stub de slippage +2 produce riesgo efectivo de 150 tras sizing de 50. p=NaN con bool=true deja pasar el cap. Barrido de 36 casos finitos en rejillas normales pasa.','Reserva no es riesgo inicial. La garantía previa no cubre fills distintos. NaN es prueba defensiva, no afirmación sobre OrderCalcProfit real. Un centavo tampoco equivale a límite matemático exacto.','Separar riesgo inicial durable, actual y pendiente; conciliar fill/barreras y finitud. No cambiar kernel/tolerancia sin contrato y paridad. Propuesta sólo rechaza p no finito.')
finding('F13','High','Frescura puntual no protege envío tras degradación de conexión/ticks',[(E,'PositiveSpread',160),(E,'SendEntry',303),(E,'ArmGate',123),(C,'TickState',99)],'T05 T06 T54 T57 T82','Executor valida precios/spread y HB de módulos, no edad de tick ni TERMINAL_CONNECTED. Bootstrap valida frescura una vez. Cuenta demo/servidor/USD se valida en init, no directamente en SendEntry.','Con CERT y heartbeat fresco, tick positivo de hace una hora llega a Buy. connected=false también llega a Buy en el stub.','Solicitud con referencia obsoleta o ACK perdido. T82 no demuestra fill real desconectado, sólo ausencia de gate local. Cambio de cuenta puede provocar reinit de MT5: comportamiento exacto BLOCKED.','Validar cuenta/sesión/conexión y tick por solicitud con reloj autorizado; reconexión requiere reconciliación antes de entradas.')
finding('F14','High','CERT no acredita executor saludable, identidad exacta ni evidencia durable',[(C,'RuntimeFailure',249),(C,'RuntimeFailure',267),(C,'OnStart',432),(C,'WriteState',166),(E,'RuntimeCertified',132),(E,'OnTimer',490)],'T03 T04 T56 T58 T59','RuntimeFailure valida nombres de emisores y HB/ARMED del executor, no su nombre/build/hash/fault, conexión ni permiso de trading. HB se publica con g_fault. CERT=1 precede WriteState, cuyo fallo de FileOpen no lo invalida. RuntimeCertified acepta 1.5 por cast entero.','Con fault y HB fresco RuntimeFailure devuelve RUNTIME_READY. También con conexión/permiso false. CERT=1.5 habilita SendEntry. Receipt no escribible no revierte latch según OnStart/WriteState.','Readiness falso o sin receipt verificable. Nombre no es hash de EX5/SET; wrapper/START_RECEIPT adicionales bloqueados.','Certificado ligado a identidad, salud, época, cuenta y binarios; receipt durable antes del latch. Propuesta sólo exige double exacto 1.0.')
finding('F15','High','Offset estable no valida UTC+2/+3 ni DST después de certificar',[(C,'OnStart',365),(C,'RuntimeFailure',279),(C,'OnStart',445),(E,'ServerDayKey',76)],'T69 T70 T71 T72 T73 T74','Acepta cualquier offset a <=10 segundos de una hora integral tras diez observaciones. No restringe 7200/10800 ni calendario US DST. Después de CERT retorna; executor no reobserva offset.','UTC, UTC+1 y UTC-5 se estabilizan como +2/+3. Transición +2↔+3 durante precheck reinicia conteo correctamente; después de CERT no invalida latch.','Reloj certificable fuera de contrato, sin garantía central sobre DST durante operación. No se midió reloj host/broker ni se sustituyó Darwinex por America/Santiago. Calendario/sesiones y API 6182 bloqueados.','Vincular fecha/sesión al calendario Darwinex US DST autorizado, offsets permitidos y renovación tras cambio; conservar evidencia observada, no asumir UTC.')
finding('F16','High','Ledger sobrescribible y errores de escritura/timer ignorados',[(E,'LogRow',91),(E,'OnInit',460),(E,'OnInit',481),(C,'WriteState',166),(C,'OnStart',435)],'T60 T61 T62 T63','Ledger abre FILE_WRITE sin append/lectura previa ni nombre único. Ignora FileWrite/Flush. Bootstrap reabre FILE_WRITE y SHARE_READ/WRITE, cabecera+fila sin publicación atómica. EventSetMillisecondTimer no se comprueba.','Stub de apertura truncante pierde fila al reiniciar. FileWrite fallido deja envío sin fila ni fault. Timer=false retorna INIT_SUCCEEDED. FileOpen fallido sí bloquea executor.','Pérdida/lectura parcial de evidencia y ausencia del ciclo autoritativo sin fallo explícito. I/O real y parser wrapper BLOCKED; no se bloqueó CSV operativo.','Append-only o ledger por sesión, fallos I/O observables, receipt atómico y timer comprobado. Propuesta sólo resuelve timer.','infrastructure-only')
finding('F17','Low','Globals double sin límite de precisión de secuencia',[(B,'QrosBusHead',67),(B,'QrosBusPublish',101),(B,'QrosBusPublish',115)],'T50 T51','Seq/event_ms se almacenan double y recuperan long sin rango finito/integral ni rotación de época.','1788782400123 ms pasa intacto. En double, 2^53+1 coincide con 2^53; publish declara éxito sin avanzar HEAD.','No es agotamiento inminente normal; sí corrupción/persistencia sin rechazo. No se probó overflow long nativo MQL ni se certifica con JS Number.','Límites de entero exacto double y secuencia positiva/monotónica; protocolo de época.','infrastructure-only')
finding('F18','Medium','Barra, referencia y barreras efectivas carecen de contrato completo en núcleo',[(E,'GridNormalize',167),(E,'SendEntry',313),(E,'HandleModify',364),(B,'QrosBusEvent',23)],'T05 T07 T11 T26 T83','Entrada normaliza SL/TP al tick más cercano (fallback point), exige SL<Ask<TP y sólo envía BUY. Evento sin barra/generación; entry_ref sin uso. Modify TP=0 conserva anterior y SL no creciente descarta evento entero. No valida stops/freeze levels ni resultado SetTypeFillingBySymbol.','Geometría de solicitud válida puede tener stop entre Bid/Ask o muy cercano y ser rechazada. Modify sólo de TP se descarta sin subir SL. No se afirma que emisores exactos produzcan esos mensajes.','Una entrada por barra, puntos, primer toque/gap y SL primero dependen de emisor/broker exactos. Ausencia de SELL no es regresión sin contrato de módulo que lo requiera.','Importar emisores exactos y probar paridad dimensional/causal/fills; no retocar unidades/señal/stops/prioridad.')
finding('F19','High','Fuentes y activación incompletas impiden certificación integral',[(C,'OnStart',347),(E,'include Trade/Trade.mqh',9)],'X01 X02 X03 X04 X05 X06 X07 X08','Recibo declara ausentes emisores/wrapper; no hay ZIP deployment, START_RECEIPT, EX5/SET/templates ni Trade.mqh exacto 6182 en el árbol. AUTHORITY es histórico: PREREG MT5_EXTERNAL_PENDING y genealogía DIV3 previo distinto no reemplazan recibo v2.2.3.','Cuatro espejos comparados en bytes/hash/blob coinciden. Inventario Git MQ5/MQH/ZIP no contiene faltantes; único ZIP listado es baseline v0.6.','No se prueba identidad del binario activo ni paridad/certificados de activación/broker. Se conserva afirmación del usuario de forward activo; no se contradice con prereg histórico.','BLOCKED_PENDING_EXACT_SOURCE_IMPORT. Importar append-only verificado y gate aislado; no sustituir con main ni inspeccionar terminal activo.','infrastructure-only','BLOCKED')
def write_json(name,value):
 (BASE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
frozen=json.loads((BASE/'evidence/frozen-final/stdout.json').read_text())
proposal=json.loads((BASE/'evidence/proposal-final/stdout.json').read_text())
bytest={}
for f in F:
 for tid in f['test_ids']: bytest.setdefault(tid,[]).append(f['id'])
for t in frozen:
 t.update(finding_ids=bytest.get(t['id'],[]),evidence_file='evidence/frozen-final/stdout.json',native_mt5_validation='BLOCKED',native_mt5_observed_result=None)
missing=[('X01','Emisor XAU exacto','Reconstrucción, una entrada/barra, SL/TP y prioridad'),('X02','Emisor NQX 17/31 exacto','Perfil, reloj, causalidad y reconstrucción'),('X03','Emisor DIV3 exacto','Gestión, warmup, fechas y heartbeat'),('X04','Wrapper PowerShell exacto','Exclusión de instancias, compilación, CSV parcial y deployment gate'),('X05','Trade.mqh/dependencias build 6182','CTrade bool/retcode, filling, visibilidad, timeout y gestión reales'),('X06','ZIP y EX5/SET/templates exactos','Identidad bytes y cadena compilación/parámetros'),('X07','START_RECEIPT y ZIP de activación','Arranque armado y certificados exactos'),('X08','Oráculos/certificados padre-hijo/controlador','Paridad canónica y module certs misma build')]
blocked=[]
for id,title,expected in missing:
 blocked.append(dict(id=id,title=title,expected_result=expected,observed_result=None,status='BLOCKED',classification='BLOCKED',reason='BLOCKED_PENDING_EXACT_SOURCE_IMPORT',finding_ids=['F19']))
platform=[('X09','Gap stop/target, SL primero, Bid/Ask','Replay aislado TEST_ONLY de ambigüedad/gap, primer precio ejecutable, no EOF inventado'),('X10','Dos MT5 en cuenta aislada','Fencing y contabilidad con visibilidad retrasada'),('X11','Restart Windows/MT5 y durabilidad','Crash aislado en cada commit, boot con posiciones/órdenes existentes'),('X12','Reconexión, rechazo, partial y ACK reales','Trade fixture o broker demo aislado con órdenes/deals/SL/TP/volumen/retcodes originales'),('X13','US DST UTC+2/+3 y medianoche','Antes/durante/después de transición con calendario autorizado y reloj registrado'),('X14','Auto-update aislado','Invalidación identidad/build y gate 0/0 posterior'),('X15','CSV bloqueado/parcial real','Inyectar I/O aislado; wrapper rechaza receipt parcial/viejo'),('X16','Compilación y aceptación nativas','MetaEditor 6182 0/0, paridad, canary y START_RECEIPT aislados')]
for id,title,expected in platform:
 blocked.append(dict(id=id,title=title,expected_result=expected,observed_result=None,status='BLOCKED',classification='BLOCKED',reason='OFFLINE_BOUNDARY_NO_ISOLATED_MT5_BUILD_6182_EXECUTION',finding_ids=[]))
coverage=[('D01','two entries same millisecond',['T13','T14','T15']),('D02','fourth daily entry',['T12','T35','T36']),('D03','zero/crossed spread',['T05']),('D04','stale startup ring',['T33','T34']),('D05','duplicate/torn sequence',['T41','T42','T44','T79','T86']),('D06','overflow >32',['T43','T27']),('D07','broker rejection',['T16','T23','T24','T39','X05','X12']),('D08','partial fill',['T18','T25','X12']),('D09','disconnect before ACK',['T19','T82','X12']),('D10','stop modification rejection',['T23','T80','X05']),('D11','restart open position',['T30','T31','T32','T34','T65','X01','X02','X03','X11']),('D12','persistent globals restart',['T33','T45','T48','T55','T78','X11']),('D13','server midnight',['T37','T38','T39','T40','T74','T81','X13']),('D14','US DST transition',['T69','T70','T71','T72','T73','X13']),('D15','gap SL/TP',['T21','X09']),('D16','two terminals',['T46','T66','T75','X04','X10']),('D17','temporary trade forbidden',['T29','T59','X12']),('D18','terminal auto-update',['X06','X14','X16']),('D19','locked/partial CSV',['T60','T61','T62','X04','X15']),('D20','late init/heartbeat expiry',['T54','T55','T56','T57'])]
counts=lambda rows:{s:sum(t['status']==s for t in rows) for s in ['PASS','FAIL','BLOCKED']}
changes=[a['id'] for a,b in zip(frozen,proposal) if a['status']=='FAIL' and b['status']=='PASS']
regressions=[a['id'] for a,b in zip(frozen,proposal) if a['status']=='PASS' and b['status']!='PASS']
if regressions: raise RuntimeError('proposal regressions '+str(regressions))
write_json('CODEX_AUDIT_FINDINGS.json',{'schema':'QROS_V223_OFFLINE_FINDINGS_1','findings':F})
write_json('CODEX_AUDIT_TEST_MATRIX.json',{'schema':'QROS_V223_OFFLINE_TEST_MATRIX_1','audited_head':HEAD,'branch':BRANCH,'source_authority':'FROZEN_SOURCE_RECEIPT.json','scope':'OFFLINE_TEST_ONLY_SOURCE_TRANSLATION_AND_STATIC_REVIEW','classification_legend':{'STATIC_PROVEN':'Direct fact of exact source','TEST_PROVEN':'Executed translated-source probe with scripted APIs only; not MT5','INFERRED':'Conditional consequence under stated assumptions','BLOCKED':'Missing exact input/isolated execution, null observed_result'},'summary':counts(frozen+blocked),'executed_probe_count':len(frozen),'executed_probe_summary':counts(frozen),'blocked_native_or_source_cases':len(blocked),'tests':frozen+blocked,'required_D_coverage':[dict(id=i,requirement=n,test_ids=ts) for i,n,ts in coverage],'proposal':{'scope':'PARTIAL_CONTAINMENT_NOT_DEPLOYABLE','summary':counts(proposal),'improved_expectations':changes,'regressed_expectations':regressions,'evidence':'evidence/proposal-final/stdout.json','native_compile_status':'BLOCKED'},'process_exit_zero_meaning':'Probe completed; FAIL rows remain product expectation failures.'})
write_json('CODEX_AUDIT_DECISION.json',{'schema':'QROS_V223_OFFLINE_AUDIT_DECISION_1','decision':'CRITICAL_REPLACEMENT_REQUIRED','classification':'INFERRED','decision_basis':'Critical safety gaps in exact source, corroborated by deterministic transcription probes. No active incident observed.','audit_scope_status':'OFFLINE_AUDIT_COMPLETE_FOR_AVAILABLE_EXACT_SOURCES_WITH_EXPLICIT_BLOCKS','audited_branch':BRANCH,'audited_parent_head':HEAD,'critical_findings':['F01','F03','F04'],'frozen_source_identity_status':'PASS_4_OF_4_MIRRORED_SOURCES_BYTES_SHA256_GIT_BLOB','any_frozen_file_modified':False,'runtime_or_terminal_touched':False,'deployment_performed':False,'merge_performed':False,'holdout_or_real_ticks_accessed':False,'economic_results_computed':False,'native_mt5_executed':False,'active_incident_observed':False,'forward_active_at_handoff':'USER_CONFIRMED_NOT_INDEPENDENTLY_INSPECTED','test_summary':counts(frozen+blocked),'proposal_status':'PARTIAL_CONTAINMENT_NOT_DEPLOYABLE','unresolved_source_status':'BLOCKED_PENDING_EXACT_SOURCE_IMPORT','replacement_requires':['exact source imports verified','MetaEditor compile 0 errors/0 warnings on isolated authorized host','parent-child parity','controller parity','forward module certificates','combined canary','exact START_RECEIPT','armed runtime CERT=1 after complete gate'],'operational_boundary':'Engineering requirement; no automatic replacement/restart/recompile/intervention in active terminal.','report':'CODEX_AUDIT_REPORT.md','matrix':'CODEX_AUDIT_TEST_MATRIX.json','commit_identity_note':'Delivered commit SHA comes from Git after commit; not stored self-referentially.'})
function_inventory=[]
for path in [E,B,R,C]:
 src=(BASE/path).read_text()
 for m in re.finditer(r'^\s*(?:void|bool|int|long|ulong|double|string|datetime)\s+(\w+)\s*\(',src,re.M):
  name=m.group(1); start=src.index('{',m.end()); depth=1;end=start+1
  while depth and end<len(src):
   if src[end]=='{': depth+=1
   elif src[end]=='}': depth-=1
   end+=1
  line=src.count('\n',0,re.search(r'\S',src[m.start():m.end()]).start()+m.start())+1
  function_inventory.append(dict(file=path,function=name,line=line,end_line=src.count('\n',0,end)+1,review='STATIC_PROVEN',dynamic_scope='STATIC_ONLY' if path==C and name in ['CloseOtherCharts','WriteState','WriteEarlyFail','OnStart'] else 'TRANSLATED_BODY_AVAILABLE_NOT_BRANCH_COVERAGE_CERTIFICATION'))
write_json('evidence/FUNCTION_REVIEW_INVENTORY.json',{'scope':'All function bodies read; no statement/MC/DC coverage claim','functions':function_inventory})
write_json('evidence/HARNESS_ATTEMPTS.json',{'attempts':[{'run':'run-01','exit_code':1,'result':'HARNESS_ERROR_datetime_cast_not_translated','artifact':'run-01/stderr.txt','product_tests_observed':False},{'run':'run-02','exit_code':0,'tests':68,'PASS':30,'FAIL':38},{'run':'run-03','exit_code':1,'result':'HARNESS_ERROR_offset_source_slice_whitespace','product_tests_observed':False},{'run':'run-04','exit_code':0,'tests':80,'PASS':34,'FAIL':46},{'run':'proposal-01','exit_code':0,'tests':80,'PASS':44,'FAIL':36},{'run':'frozen-final','exit_code':0,'tests':87,'PASS':38,'FAIL':49},{'run':'proposal-final','exit_code':0,'tests':87,'PASS':49,'FAIL':38}],'historical_import_precheck':{'command':'python3 handoff/verify_import.py','initial_result':'python3 not found','retry':'bundled Python executable, same script','exit_code':1,'observed':'ValueError: changed file: AGENTS.md','interpretation':'Baseline verifier rejects preexisting descendant changes; tree clean before audit. v2.2.3 exact source integrity verified separately.'},'compiler_preflight':{'g++_clang_cl_on_PATH':'NOT_FOUND','common_msys_llvm_paths':'NOT_FOUND','wsl_list_verbose':'exit 1 usage; no usable distribution established','MetaEditor':'NOT_INVOKED_ACTIVE_TERMINAL_PROTECTED','downloads_or_installs':False},'artifact_writer_attempt':{'result':'Windows CreateProcess 206 for oversized command; no file written; split into bounded commands','product_test_effect':'NONE'}})
report=['''# Auditoría offline Darwinex-Demo v2.2.3 congelado

Decisión: **CRITICAL_REPLACEMENT_REQUIRED** (`INFERRED`, recomendación de ingeniería apoyada en defectos `STATIC_PROVEN` y contraejemplos `TEST_PROVEN` de alcance sintético).

No se ha demostrado un incidente en el forward activo. El terminal operativo permanece fuera de la auditoría. La decisión exige reemplazo corregido y certificado; no autoriza instalar la propuesta parcial, detener/reiniciar el terminal ni desplegar. No concede aceptación científica ni live.

## Alcance, identidad y método

`TEST_PROVEN`: rama `audit/demo-forward-v2.2.3-frozen-20260907`, HEAD inicial `3c92d2ca50fb08d3b51d19f6f042f328797460e4`, árbol limpio antes de crear artefactos. Cuatro fuentes centrales coinciden en longitud, SHA-256 y Git blob SHA-1 con FROZEN_SOURCE_RECEIPT. Se conservan los seis archivos frozen/, tres documentos iniciales v2.2.3 y evidencia histórica. `evidence/INTEGRITY_FINAL.json` registra comparación final contra Git.

`STATIC_PROVEN`: el recibo identifica ZIP de 134189 bytes y SHA-256 `6e732d59808b768d84ad3a1f734a08a608262192c1f78b2e7143141b461fccde`. El ZIP no está presente: ese hash NO se verificó contra sus bytes. Executor, bus, kernel, bootstrap y autoridades congeladas se leyeron íntegramente, además del handoff/AGENTS requerido. El encargo actual no se sustituye por la antigua construcción C++.

`BLOCKED_PENDING_EXACT_SOURCE_IMPORT` (`BLOCKED`): tres emisores, wrapper, package/EX5/SET/templates, Trade.mqh/dependencias 6182, START_RECEIPT/evidencia de activación y oráculos exactos. No se usó fuente aproximada, main ni directorio del terminal. La declaración del usuario de forward activo se conserva; PREREG histórico no es receipt de activación actual.

`TEST_PROVEN` significa ejecución real del banco offline: traducción acotada y revisable de los cuerpos del executor/bus/kernel, siete funciones bootstrap y su bloque de offset a Node, con fronteras API programadas. Se retienen código generado, stdout JSON, stderr y recibos. No se ejecutó EX5, MetaEditor, Trade.mqh, broker ni dos terminales. Booleano/retcode, posiciones/deals, crashes y cotizaciones son fixtures adversariales explícitas. No se calcula rendimiento ni se consultan datos económicos.

`INFERRED`: la traducción conserva flujo/formulas del subconjunto inspeccionado; no prueba equivalencia formal MQL5. Enteros JS son exactos hasta 2^53−1; T51 estudia doubles de globals, no overflow long MQL. Stubs de archivo, reloj, profit y visibilidad modelan supuestos declarados. Ninguna observación se convierte en resultado MT5. CTrade exacto 6182 queda bloqueado. No se consultó web durante la auditoría offline. Los recibos originales de traducción guardan hash del texto UTF-8 LF antes de escribir CRLF en Windows; TRANSLATION_HASH_VERIFICATION.json verifica ese hash y agrega el hash de archivo real sin reescribir evidencia. ARTIFACT_MANIFEST liga los bytes finales.

`TEST_PROVEN`: `handoff/verify_import.py` falló en AGENTS.md, ya distinto del handoff original antes de auditar. python3 no estaba en PATH; se repitió el mismo script con Python bundled. No se reescribió manifest para ocultar el resultado. No se estableció C++/WSL utilizable ni se instalaron herramientas. Suites C++ v0.6 no validan este executor MQL5 y no se presentan como evidencia de él.

## Resultados ejecutados

`TEST_PROVEN` de fuente traducida: **87 escenarios, 38 PASS y 49 FAIL** en v2.2.3. La matriz añade **16 BLOCKED** de fuentes o ejecución nativa. Cada FAIL compara con expectativa segura, nunca con la expectativa de reproducir un defecto. Exit 0 sólo indica observaciones serializadas; no es gate verde. Errores iniciales del harness se conservan separados en HARNESS_ATTEMPTS.json.

`TEST_PROVEN` de propuesta parcial: **49 PASS y 38 FAIL**, once expectativas mejoradas sin perder los 38 PASS originales. No equivale a compilación/paridad MT5. Reconciliación, recovery y bus conservan defectos críticos.

Resultados: CODEX_AUDIT_TEST_MATRIX.json, `evidence/frozen-final/stdout.json` y `evidence/proposal-final/stdout.json`. FUNCTION_REVIEW_INVENTORY.json enumera cada función revisada. No se afirma MC/DC, fuzzing exhaustivo ni cobertura de todo schedule concurrente.

## Trazado completo del núcleo exacto

`STATIC_PROVEN`: emisor exacto [bloqueado] → QrosBusPublish (payload → SEQ → HEAD) → PollBus. ENTRY → AddPending → SortPending/ProcessPending → SendEntry → símbolo/magic → fault/recovery/CERT/HB/spread → día/cupo/timestamp/activo → normalización/sizing → reserva → arm → CTrade.Buy → bool/retcode → contador, DAY/LASTEV y ledger. Falta reconciliación posterior orden/deal/posición/volumen/barreras.

`STATIC_PROVEN`: MODIFY_SL/CLOSE saltan buffer y buscan primera posición por símbolo/magic. Modify sólo eleva SL; Close intenta ticket. Ambos descartan intención tras CTrade y usan bool para EXECUTED. ForceNoOvernight recorre posiciones y compara fechas, normalmente en timer después de RefreshDay. g_fault salta esas rutas en ciclos futuros. OnInit descarta todos los records hasta HEAD, pone CERT=0 y recovery lock sólo si hay posiciones.

`STATIC_PROVEN`: bootstrap pone CERT=0, valida cuenta/flat, cierra otros charts, limpia HB/STATE, aplica templates, espera nombres/READY/HB/ticks/series/arm/offset/flat, pone CERT=1 si ExpectedArmed==1, intenta receipt y termina. Aunque no tenga order API, CloseOtherCharts/ChartApplyTemplate mutan el terminal: nunca se ejecutó este script aquí.

## Hallazgos

Los números de línea pertenecen a frozen/, no a la propuesta.
''']
report.append('| ID | Severidad | Clasificación de fuente | Hallazgo |\n|---|---|---|---|\n'+''.join(f"| {f['id']} | {f['severity']} | {f['classification']} | {f['title']} |\n" for f in F))
for f in F:
 report.append('\n### '+f['id']+' — '+f['title']+'\n')
 report.append(f"Severidad: **{f['severity']}**. Semántica: `{f['semantic_class']}`.\n")
 report.append('Ubicación exacta: '+'; '.join(f"`{x['file']}:{x['line']}` `{x['function']}`" for x in f['locations'])+'.\n')
 report.append(f"`{f['classification']}` — {f['source_conclusion']}\n")
 report.append('Escenario/reproducibilidad: '+f['deterministic_scenario']+' Casos: '+', '.join(f['test_ids'])+'. Los T son `TEST_PROVEN` en el harness; X son `BLOCKED`.\n')
 report.append('`INFERRED` — Consecuencia/exposición activa: '+f['consequence']['text']+' '+f['active_v223_exposure']['text']+'\n')
 report.append('Corrección propuesta (`INFERRED`): '+f['proposed_correction']+'\n')
report.append('''
## Controles demostrados y límites

- `STATIC_PROVEN` y T01–T03 (`TEST_PROVEN`): demo, Darwinex-Demo y USD se validan al iniciar; desarmado o CERT=0 no envían Buy. Nombre/arm token de código no autentican EX5.
- `TEST_PROVEN`: spread cero/cruzado bloqueado; kernel usa OrderCalcProfit de 1 lote y volumen efectivo, floor por step y rechazo de mínimo excesivo. Barrido de 36 casos más BUY/SELL del kernel pasa. Executor usa Ask para sizing y Buy(price=0); fill efectivo, Bid de salida, gap y SL primero requieren broker/emisor exactos. No se inventan fills/EOF.
- `TEST_PROVEN`: cupo 3, activo ocupado y reserva visible sobre cap se bloquean sin incertidumbre. Historial completo deduplica fills de igual position ID. No generalizar a pendientes, historia fallida o netting.
- `TEST_PROVEN`: prioridad en cohorte coetánea, consumo único por seq, slot ausente/SEQ que cambia, overflow >32 y skip HEAD inicial. No generalizar a payload sobrescrito antes de commit, rollback o dos productores.
- `TEST_PROVEN`: recovery lock permite CLOSE nuevo; timer sano cierra posición de día anterior. No prueba reconstrucción, no overnight estricto ni unlock.
- `TEST_PROVEN`: bootstrap comprueba nombres de emisores/posición/ticks/series en funciones probadas. HB vencido o estado no READY bloquea entrada, uptime futuro se rechaza y offset cambiado durante precheck reinicia conteo. No certifica continuidad postarranque.

## Escenarios obligatorios D01–D20

X representa bloqueo; diseñar fixture no equivale a ejecutarla.

| Requisito | Escenario | Casos |\n|---|---|---|
''')
for i,n,ts in coverage: report.append('| '+i+' | '+n+' | '+', '.join(ts)+' |\n')
report.append('''
## Bloqueos, decisión y propuesta

`BLOCKED`: fuentes faltantes/pruebas nativas tienen observed_result=null. No se inspeccionó MT5 operativo para conseguirlas ni se recuperaron bytes de otro repo/red. La única red para entregar es Git sobre la rama autorizada.

`INFERRED`: F01 y F03 bastan para **CRITICAL_REPLACEMENT_REQUIRED**: faltan reservas de exposición pendiente y existen caminos que suprimen gestión central futura. F04 agrega recuperación insuficiente ante protección/intención perdida. Emisores ausentes bloquean certificación del conjunto, pero no borran defectos del executor exacto. No se estima probabilidad de pérdida ni se afirma que ocurrieran en Darwinex.

`BLOCKED`: ni test count ni compilación bastan para promocionar. Falta importar fuentes exactas y gate completo: compile 0/0, parent-child parity, controller parity, forward module certs, combined canary, START_RECEIPT, armado CERT=1. Contención/contrato se crean únicamente en proposed/v2.2.4/; nada se cambia en frozen/.

## Reproducibilidad y entrega

Desde raíz con Python 3/Node ya disponibles, sin instalaciones:

```text
python audit/demo-forward-v2.2.3/tests/run_offline_audit.py --node <node-executable> --out audit/demo-forward-v2.2.3/evidence/<nuevo-directorio>
python audit/demo-forward-v2.2.3/tests/run_offline_audit.py --node <node-executable> --out audit/demo-forward-v2.2.3/evidence/<otro-directorio> --proposal
```

`STATIC_PROVEN`: runner rechaza hashes diferentes y exige salida nueva dentro de la auditoría. Generated JS/resultados son TEST_ONLY; stubs/scenarios no son runtime publicado ni sustituyen C++.

`TEST_PROVEN`: revisión final compara bytes de todos los paths iniciales de audit/demo-forward-v2.2.3 con Git HEAD y cuatro espejos con recibo. INTEGRITY_FINAL.json guarda resultado; ARTIFACT_MANIFEST liga nuevos artefactos SHA-256. SHA del commit se obtiene después y se comunica desde Git, sin hash autorreferente. Push limitado a esta rama, sin merge a main.
''')
report_text=re.sub(r'(?m)^(\|[^\n]*\|)\n+(?=\|)',r'\1\n','\n'.join(report))
(BASE/'CODEX_AUDIT_REPORT.md').write_text(report_text.rstrip()+'\n',encoding='utf-8')
print(json.dumps({'findings':len(F),'tests':len(frozen),'blocked':len(blocked),'source_functions_reviewed':len(function_inventory),'proposal_improvements':changes}))
