// Every PASS/FAIL is against a safety expectation, never against reproducing a bug.
const RESULTS=[];
function test(id,title,expected,fn){reset();const r=fn();RESULTS.push({id,title,expected_result:expected,observed_result:r.observed,status:r.safe?'PASS':'FAIL',classification:'TEST_PROVEN',scope:'TEST_ONLY_SOURCE_TRANSLATION_SCRIPTED_API'});}
function outcome(safe,observed){return {safe,observed};}
function accepted(){return S.rows.filter(r=>r[2]==='ENTRY'&&r[3]==='EXECUTED').length;}
function boot(overrides={}){return RuntimeFailure(1,2,3,0,0,0,0,true,true,true,true,true,10,1,...[]);}

test('T01','Demo account gate','Reject live mode',()=>{S.account.mode=2;return outcome(!DemoAccountGate()&&g_fault,{fault:g_fault,reason:g_fault_reason});});
test('T02','Server and currency gates','Reject wrong server and currency',()=>{S.account.server='other';let a=!DemoAccountGate();reset();S.account.currency='EUR';let b=!DemoAccountGate();return outcome(a&&b,{wrong_server_blocked:a,wrong_currency_blocked:b});});
test('T03','Armed certification gate','No Buy with CERT=0 or arm=false',()=>{S.gv.set('QDB1.EXEC.CERT',0);let a=!SendEntry(event());reset();InpArmDemoOrders=false;let b=!SendEntry(event());return outcome(a&&b&&S.requests.length===0,{cert_blocks:a,unarmed_blocks:b});});
test('T04','Runtime certificate exact value','Reject fractional CERT value',()=>{S.gv.set('QDB1.EXEC.CERT',1.5);let sent=SendEntry(event());return outcome(!sent,{cert:1.5,sent});});
test('T05','Zero and crossed spread','Reject both before Buy',()=>{S.ticks.XAUUSD.ask=99;let a=!SendEntry(event());S.ticks.XAUUSD.ask=98;let b=!SendEntry(event());return outcome(a&&b&&!S.requests.length,{zero_blocked:a,crossed_blocked:b,requests:S.requests.length});});
test('T06','Fresh executable quote after certification','Stale positive spread must block',()=>{S.ticks.XAUUSD.time-=3600;S.ticks.XAUUSD.time_msc-=3600000;let sent=SendEntry(event());return outcome(!sent,{quote_age_sec:3600,sent});});
test('T07','BUY Ask and floor volume','Risk sized at Ask <=50 USD with volume floor',()=>{S.spec.step=0.03;S.spec.min=0.03;let sent=SendEntry(event());return outcome(sent&&S.requests[0].volume===0.48&&risk()<=50,{volume:S.requests[0]?.volume,initial_risk:risk(),buy_price_argument:S.requests[0]?.price});});
test('T08','Minimum size exceeds risk','Reject rather than increase minimum volume',()=>{S.spec.min=1;let sent=SendEntry(event());return outcome(!sent&&!S.requests.length,{sent,decision:decision()});});
test('T09','OrderCalcProfit failure','Block sizing failure',()=>{S.profit_ok=false;let sent=SendEntry(event());return outcome(!sent&&!S.requests.length,{sent});});
test('T10','Risk cap visible positions','Reject 60 USD reserved + 50 USD proposed',()=>{position(1,{volume:0.6});let sent=SendEntry(event(2));return outcome(!sent,{reserved:risk(),sent});});
test('T11','One visible position per asset','Block NDX entry if any NDX position exists',()=>{position(2,{magic:999});let sent=SendEntry(event(3));return outcome(!sent,{sent,positions:S.positions.length});});
test('T12','Three entries then fourth','Fourth sequential entry blocked',()=>{for(let i=0;i<3;i++){SendEntry(event(1,S.now*1000+i));S.positions=[];}let fourth=SendEntry(event(1,S.now*1000+4));return outcome(!fourth&&S.requests.length===3,{fourth,requests:S.requests.length,count:g_day_entries});});
test('T13','Same millisecond and cohort priority','XAU wins and only one entry accepted',()=>{AddPending(event(3));AddPending(event(2));AddPending(event(1));S.uptime+=300;ProcessPending();return outcome(S.requests.length===1&&S.requests[0].symbol==='XAUUSD',{requests:S.requests.map(x=>x.symbol),accepted:accepted()});});
test('T14','Priority across buffer ages','Do not send lower priority while known same-ms XAU waits',()=>{AddPending(event(2));S.uptime+=100;AddPending(event(1));S.uptime+=200;ProcessPending();return outcome(!S.requests.length||S.requests[0].symbol==='XAUUSD',{requests:S.requests.map(x=>x.symbol),pending:g_pending.length});});
test('T15','Nonmonotonic repeated timestamp','Timestamp A accepted once even after timestamp B',()=>{const a=S.now*1000;SendEntry(event(1,a));S.positions=[];SendEntry(event(1,a+1));S.positions=[];let again=SendEntry(event(1,a));return outcome(!again,{again,requests:S.requests.length,last:g_last_accepted_event_ms});});
test('T16','Broker rejection','No daily state committed after explicit rejection',()=>{S.responses.push({ok:true,rc:REJECT});let sent=SendEntry(event());return outcome(!sent&&g_day_entries===0&&g_last_accepted_event_ms===-1,{sent,count:g_day_entries,last:g_last_accepted_event_ms});});
test('T17','PLACED delayed visibility risk and asset reservation','Outstanding orders reserve asset and risk; maximum 100 USD',()=>{for(let i=0;i<3;i++){S.responses.push({ok:true,rc:TRADE_RETCODE_PLACED,pending:true});SendEntry(event(i===0?1:2,S.now*1000+i));}return outcome(S.orders.filter(o=>o.symbol==='NDX').length<=1&&risk()<=100,{orders:S.orders.length,positions:S.positions.length,total_initial_reserved:risk(),count:g_day_entries});});
test('T18','DONE_PARTIAL and remaining volume','Reserve unfilled remainder, plus all other outstanding orders',()=>{S.responses.push({ok:true,rc:TRADE_RETCODE_DONE_PARTIAL,pending:true,visible:0.5});SendEntry(event());for(let i=1;i<=2;i++){S.responses.push({ok:true,rc:TRADE_RETCODE_PLACED,pending:true});SendEntry(event(2,S.now*1000+i));}return outcome(risk()<=100&&S.orders.filter(o=>o.symbol==='NDX').length<=1,{risk:risk(),position_volume:S.positions[0].volume,pending_volumes:S.orders.map(o=>o.volume)});});
test('T19','Disconnect after send before acknowledgement','Ambiguous send reserves asset until reconciliation',()=>{S.responses.push({ok:false,rc:TIMEOUT,pending:true});SendEntry(event());let second=SendEntry(event(1,S.now*1000+1));return outcome(!second,{second,outstanding_orders:S.orders.length,positions:S.positions.length,count:g_day_entries});});
test('T20','PLACED later cancelled','Reconcile accepted entry count to broker terminal outcome',()=>{S.responses.push({ok:true,rc:TRADE_RETCODE_PLACED,pending:true});SendEntry(event());S.orders=[];OnTimer();return outcome(g_day_entries===0,{count:g_day_entries,actual_deals:S.deals.length});});
test('T21','Actual fill price risk','Reconcile slippage before certifying 0.5 percent initial risk',()=>{S.responses.push({ok:true,rc:TRADE_RETCODE_DONE,visible:1,slippage:2});let sent=SendEntry(event());return outcome(!sent||risk()<=50,{sent,logged:decision(),actual_initial_risk:risk()});});
test('T22','DONE without protection','Do not declare execution complete without reconciling actual SL/TP',()=>{S.responses.push({ok:true,rc:TRADE_RETCODE_DONE,visible:1,unprotected:true});SendEntry(event());OnTimer();return outcome(S.positions.length===0||S.positions[0].sl>0,{positions:S.positions.length,sl:S.positions[0]?.sl,fault:g_fault,entry_executed:accepted()});});
test('T23','PositionModify server rejection','Never log EXECUTED when retcode rejects and SL unchanged',()=>{position();S.modify={ok:true,rc:REJECT,apply:false};let e=event();e.sl=99.5;HandleModify(e);return outcome(decision()!=='EXECUTED',{decision:decision(),retcode:g_trade.ResultRetcode(),sl:S.positions[0].sl});});
test('T24','PositionClose server rejection','Never log EXECUTED while position remains open',()=>{position();S.close={ok:true,rc:REJECT,apply:false};HandleClose(event());return outcome(decision()!=='EXECUTED',{decision:decision(),retcode:g_trade.ResultRetcode(),positions:S.positions.length});});
test('T25','PositionClose partial response','Remaining position is unresolved, not EXECUTED',()=>{position();S.close={ok:true,rc:TRADE_RETCODE_DONE_PARTIAL,apply:false};HandleClose(event());return outcome(decision()!=='EXECUTED',{decision:decision(),positions:S.positions.length});});
test('T26','Acknowledged modify/close','Verify normal successful management',()=>{position();let e=event();e.sl=99.5;HandleModify(e);let modified=S.positions[0].sl===99.5;HandleClose(e);return outcome(modified&&!S.positions.length,{modified,positions:S.positions.length});});
test('T27','Fault with open position at day boundary','Emergency management still closes prior-day position',()=>{position(1,{time:S.now-86400});SetFault('BUS_OVERFLOW_MODULE_1');OnTimer();return outcome(!S.positions.length,{positions:S.positions.length,close_calls:S.close_calls,cert:S.gv.get('QDB1.EXEC.CERT')});});
test('T28','Fault blocks module close','Consume close while entry path faulted',()=>{position();SetFault('BUS_TORN_OR_MISSING_MODULE_1');publish(event(1,S.now*1000,0,3));OnTimer();return outcome(!S.positions.length,{positions:S.positions.length,head:QrosBusHead(1),consumed:g_last_seq[1]});});
test('T29','Temporary terminal trade disabled then restored','Resume safe management after permission restoration',()=>{position();S.trade_allowed=false;HandleClose(event());S.trade_allowed=true;S.positions[0].time-=86400;OnTimer();return outcome(!S.positions.length,{fault:g_fault,positions:S.positions.length,close_calls:S.close_calls});});
test('T30','Restart open position remains module-manageable','Recovery lock blocks entry but does not itself block new close event',()=>{position();let init=OnInit();publish(event(1,S.now*1000,0,3));OnTimer();return outcome(init===0&&g_recovery_lock&&!S.positions.length,{init,recovery_lock:g_recovery_lock,positions:S.positions.length,cert:S.gv.get('QDB1.EXEC.CERT')});});
test('T31','Recovery lock release flat plus recertification','Flat and recertified executor has reachable unlock',()=>{position();OnInit();S.positions=[];S.gv.set('QDB1.EXEC.CERT',1);OnTimer();let sent=SendEntry(event());return outcome(sent,{recovery_lock:g_recovery_lock,sent});});
test('T32','Restart unprotected position same day','Detect and reconcile missing SL before leaving position unmanaged',()=>{position(1,{sl:0});OnInit();OnTimer();return outcome(S.positions.length===0||S.positions[0].sl>0,{recovery_lock:g_recovery_lock,fault:g_fault,positions:S.positions.length,sl:S.positions[0]?.sl});});
test('T33','Restart discards stale entry ring','No stale startup entry replay',()=>{publish(event());OnInit();OnTimer();S.uptime+=300;ProcessPending();return outcome(!S.requests.length,{head:QrosBusHead(1),last_seq:g_last_seq[1],requests:S.requests.length});});
test('T34','Restart discards queued close','Existing position is reconciled despite startup queue discard',()=>{position();publish(event(1,S.now*1000,0,3));OnInit();OnTimer();return outcome(!S.positions.length,{positions:S.positions.length,last_seq:g_last_seq[1]});});
test('T35','Successful history rebuild counts unique position IDs','Partial deal split counts one entry; fourth remains blocked',()=>{S.deals=[{magic:560101,entry:0,pid:1},{magic:560101,entry:0,pid:1},{magic:560217,entry:0,pid:2},{magic:560300,entry:0,pid:3}];RebuildDailyCount();let sent=SendEntry(event());return outcome(g_day_entries===3&&!sent,{count:g_day_entries,sent});});
test('T36','History unavailable after restart','HistorySelect failure blocks entry until authoritative rebuild',()=>{S.history_ok=false;S.deals=[1,2,3].map(pid=>({magic:560101,entry:0,pid}));RebuildDailyCount();let sent=SendEntry(event());return outcome(!sent,{sent,count:g_day_entries,actual_prior_entries:S.deals.length,fault:g_fault});});
test('T37','No overnight before server midnight','Position must be flat before crossing server day',()=>{S.now=Date.UTC(2026,8,7,23,59,59)/1000;position();OnTimer();return outcome(!S.positions.length,{positions_at_235959:S.positions.length,close_calls:S.close_calls});});
test('T38','First timer after midnight','Healthy prior-day position closes on first next-day timer',()=>{position(1,{time:S.now-86400});OnTimer();return outcome(!S.positions.length,{positions:S.positions.length,close_calls:S.close_calls});});
test('T39','Midnight close rejection','No false forced-close success',()=>{position(1,{time:S.now-86400});S.close={ok:true,rc:REJECT,apply:false};OnTimer();return outcome(decision()!=='EXECUTED',{positions:S.positions.length,decision:decision(),retcode:g_trade.ResultRetcode()});});
test('T40','Server day rollover','Count rebuilds for new server day',()=>{g_day_entries=3;S.now+=86400;RefreshDay();return outcome(g_day_entries===0,{count:g_day_entries,day:g_last_day_key});});
test('T41','Bus ordinary duplicate polling','Each sequence consumed once',()=>{publish(event());PollBus();PollBus();return outcome(g_pending.length===1,{pending:g_pending.length,last_seq:g_last_seq[1]});});
test('T42','Torn or missing SEQ','Fault on committed-head missing slot',()=>{S.gv.set(QrosBusKey(1,'HEAD'),1);PollBus();return outcome(g_fault&&!S.requests.length,{fault:g_fault,reason:g_fault_reason});});
test('T43','Overflow 33 records','Detect overflow and block entries',()=>{for(let i=0;i<33;i++)publish(event(1,S.now*1000+i));PollBus();return outcome(g_fault&&!S.requests.length,{fault:g_fault,reason:g_fault_reason,head:QrosBusHead(1)});});
test('T44','Old commit during ring overwrite','Reject payload overwritten before SEQ invalidation',()=>{for(let i=1;i<=32;i++)publish(event(1,i));S.onSet=(k,v)=>{if(k===QrosBusSlotKey(1,1,'SEQ'))throw Error('scheduled_pause_before_commit');};try{publish(event(1,33));}catch(e){if(e.message!=='scheduled_pause_before_commit')throw e;}S.onSet=null;let ev=new QrosBusEvent();let read=QrosBusRead(1,1,ev);return outcome(!read||ev.event_ms===1,{accepted:read,requested_sequence:1,returned_sequence:ev.seq,returned_event_ms:ev.event_ms,head:QrosBusHead(1)});});
test('T45','Crash after slot commit before HEAD','Unannounced record must not be falsely acknowledged as published',()=>{S.onSet=(k,v)=>k===QrosBusKey(1,'HEAD')?false:true;let ok=publish(event());PollBus();return outcome(!ok,{publisher_success:ok,head:QrosBusHead(1),pending:g_pending.length,committed_slot:S.gv.get(QrosBusSlotKey(1,1,'SEQ'))});});
test('T46','Same-module concurrent publishers','Two successful publications occupy distinct sequences',()=>{let injected=false;S.onSet=(k,v)=>{if(!injected&&k===QrosBusSlotKey(1,1,'A')){injected=true;publish(event(1,2));}return true;};let ok=publish(event(1,1));S.onSet=null;return outcome(QrosBusHead(1)===2,{outer_success:ok,both_invoked:injected,head:QrosBusHead(1)});});
test('T47','Different modules independent rings','All three modules have independent heads',()=>{for(let m=1;m<=3;m++)publish(event(m));PollBus();return outcome(g_pending.length===3&&[1,2,3].every(m=>QrosBusHead(m)===1),{pending:g_pending.length,heads:[1,2,3].map(QrosBusHead)});});
test('T48','HEAD regression after persistence rollback','Detect head less than already consumed sequence',()=>{g_last_seq[1]=10;S.gv.set(QrosBusKey(1,'HEAD'),2);PollBus();return outcome(g_fault,{fault:g_fault,last_seq:g_last_seq[1],head:QrosBusHead(1)});});
test('T49','Stale newly sequenced event','Reject old event/publish timestamp on new sequence',()=>{publish(event(1,(S.now-86400)*1000));PollBus();S.uptime+=300;ProcessPending();return outcome(!S.requests.length,{requests:S.requests.length,event_age_days:1});});
test('T50','Ring timestamp precision current epoch','Epoch milliseconds and nearby sequences retain integer precision',()=>{const t=1788782400123;publish(event(1,t));let ev=new QrosBusEvent();let ok=QrosBusRead(1,1,ev);return outcome(ok&&ev.event_ms===t,{read:ok,event_ms:ev.event_ms});});
test('T51','Double sequence upper boundary','Explicitly reject unsafe integer sequence before loss of progress',()=>{S.gv.set(QrosBusKey(1,'HEAD'),2**53);let ok=publish(event());return outcome(!ok,{success:ok,head:QrosBusHead(1),double_2pow53_plus1:2**53+1});});
test('T52','Close after buffered entry in same bus poll','Close/cancellation cannot be lost while entry waits',()=>{publish(event());publish(event(1,S.now*1000+1,0,3));PollBus();S.uptime+=300;ProcessPending();return outcome(!S.positions.length,{positions:S.positions.length,close_calls:S.close_calls,requests:S.requests.length});});
test('T53','Delayed close bound only to magic','Stale close must not close a later position generation',()=>{let e=event(1,S.now*1000-1000,0,3);position();HandleClose(e);return outcome(S.positions.length===1,{positions:S.positions.length,close_calls:S.close_calls});});
test('T54','Heartbeat expiry and late init','Block entry unless all modules READY and fresh',()=>{QrosBusSetState(3,1);let a=!SendEntry(event());QrosBusSetState(3,2);S.gv.set(QrosBusKey(3,'HB'),S.uptime-5001);let b=!SendEntry(event());return outcome(a&&b,{init_blocked:a,expired_blocked:b});});
test('T55','Windows uptime reset with globals','Reject heartbeat from future uptime',()=>{S.gv.set(QrosBusKey(1,'HB'),S.uptime+1);return outcome(!HeartbeatsReady(),{age:QrosBusHeartbeatAgeMs(1),ready:HeartbeatsReady()});});
test('T56','Bootstrap identities READY bars and protection','Ready gates pass baseline and reject each varied gate',()=>{let ready=boot();S.charts[3]='wrong';let identity=boot();S.charts[3]='QROS_DIV3_R3_DEMO_EMITTER_v2_1';position();let pos=boot();return outcome(ready==='RUNTIME_READY'&&identity==='DIV3_ID'&&pos==='QROS_POSITION_PRESENT',{ready,identity,position:pos});});
test('T57','Bootstrap freshness and synchronized bars','Reject stale ticks/unsynchronized series',()=>{let b={},a={},age={},ts={},bar={},sync={};S.ticks.XAUUSD.time-=61;let tick=TickState('XAUUSD',10800,b,a,age,ts);S.series_sync=0;let series=SeriesCurrent('NDX',15,10800,1800,bar,sync);return outcome(!tick&&!series,{tick,age:age.value,series});});
test('T58','Bootstrap executor identity and faults','Executor fault must invalidate runtime readiness',()=>{SetFault('BUS_OVERFLOW_MODULE_1');let r=boot();return outcome(r!=='RUNTIME_READY',{runtime_failure:r,fault:g_fault,exec_heartbeat_age:ExecAge()});});
test('T59','Bootstrap disconnected/trade forbidden','Reject certification when disconnected or trading disabled',()=>{S.connected=false;S.trade_allowed=false;let r=boot();return outcome(r!=='RUNTIME_READY',{runtime_failure:r,connected:false,trade_allowed:false});});
test('T60','CSV unavailable on init','Fail init if ledger cannot be opened',()=>{S.file_open=false;let r=OnInit();return outcome(r===INIT_FAILED,{init:r});});
test('T61','CSV write failure after init','Detect ledger persistence failure',()=>{S.file_write=false;let sent=SendEntry(event());return outcome(!sent||g_fault,{sent,fault:g_fault,rows:S.rows.length});});
test('T62','Ledger append across restart','Keep prior ledger rows on restart',()=>{S.rows.push(['prior_audit_record']);OnInit();return outcome(S.rows.some(r=>r[0]==='prior_audit_record'),{old_row_retained:S.rows.some(r=>r[0]==='prior_audit_record')});});
test('T63','Timer registration failure','Do not initialize authoritative-timer runtime if timer fails',()=>{S.timer_ok=false;let r=OnInit();return outcome(r!==INIT_SUCCEEDED,{init:r,timer_ok:S.timer_ok});});
test('T64','Missing SL discovered during entry risk scan','Block new entry on unknown reserved risk',()=>{position(1,{sl:0});let sent=SendEntry(event(2));return outcome(!sent&&g_fault,{sent,fault:g_fault,reason:g_fault_reason,open_unprotected:S.positions.length});});
test('T65','Unprotected restart blocks new entry','Recovery lock and CERT=0 prevent additional exposure',()=>{position(1,{sl:0});OnInit();let sent=SendEntry(event(2));return outcome(!sent,{sent,lock:g_recovery_lock,cert:S.gv.get('QDB1.EXEC.CERT')});});
test('T66','Duplicate executor instances in one terminal','Second executor init must be fenced even without a position',()=>{let first=OnInit();let second=OnInit();return outcome(first===0&&second!==0,{first,second,exclusive_lease:false});});
test('T67','Profit at moved SL is not initial risk','Retain original reservation independently of current SL',()=>{position(1,{sl:100});let ok=false;let reserved=ReservedRiskUsd({set value(v){ok=v}});return outcome(reserved===50,{calculation_ok:ok,original_initial_risk:50,reported_reserved:reserved});});
test('T68','Finite total reserved risk','Invalid numeric valuation must block new exposure',()=>{position();S.profit_nan_after=3;let sent=SendEntry(event(2));return outcome(!sent,{sent,profit_calls:S.profit_calls});});

test('T69','UTC plus 2 and plus 3 stable offsets','Both contract offsets stabilize after ten observations',()=>{let values=[];for(const off of [7200,10800]){S.offset=off;values.push(OffsetProbe(off,9,true));}return outcome(values.every(x=>x===10),{stable_counts:values});});
test('T70','Out-of-contract server UTC offset','Reject stable UTC, UTC+1 and UTC-5',()=>{let values=[];for(const off of [0,3600,-18000]){S.offset=off;values.push(OffsetProbe(off,9,true));}return outcome(values.every(x=>x<10),{offsets:[0,3600,-18000],stable_counts:values});});
test('T71','Offset transition before certification','DST offset change resets observation count',()=>{let values=[];for(const [prior,next] of [[7200,10800],[10800,7200]]){S.offset=next;values.push(OffsetProbe(prior,10,true));}return outcome(values.every(x=>x===1),{transition_counts:values});});
test('T72','Nonintegral hour offset','Reject offset outside ten-second tolerance',()=>{S.offset=10811;let n=OffsetProbe(10800,9,true);return outcome(n===0,{stable_count:n});});
test('T73','Post-certification DST transition','Revalidate CERT on server offset transition',()=>{S.offset=7200;S.gv.set('QDB1.EXEC.CERT',1);S.offset=10800;OnTimer();return outcome(S.gv.get('QDB1.EXEC.CERT')!==1,{cert:S.gv.get('QDB1.EXEC.CERT'),offset:S.offset});});
test('T74','Server day independent of host timezone','Day key follows synthetic server UTC+2/+3 timestamps',()=>{let out=[];for(const off of [7200,10800]){S.now=Date.UTC(2026,8,7,22,30)/1000+off;out.push(ServerDayKey());}return outcome(out.every(x=>x===20260908),{server_day_keys:out});});
test('T75','Independent terminal namespaces','Two independently certified controllers need account-wide ownership',()=>{SendEntry(event());let first=S.requests.length;reset();let second=SendEntry(event());return outcome(!(first&&second),{first_requests:first,second_sent:second,scope:'Independent snapshots model delayed visibility; no actual terminal instances run'});});
test('T76','Delayed position visibility with DONE','Do not treat DONE as reconciled position',()=>{S.responses.push({ok:true,rc:TRADE_RETCODE_DONE,pending:true});SendEntry(event());let second=SendEntry(event(1,S.now*1000+1));return outcome(!second,{second,orders:S.orders.length,positions:S.positions.length});});
test('T77','Close broker rejection without a fresh module event','Retry or retain unresolved close intent',()=>{position();S.close={ok:false,rc:REJECT,apply:false};HandleClose(event());S.close={ok:true,rc:TRADE_RETCODE_DONE,apply:true};OnTimer();return outcome(!S.positions.length,{positions:S.positions.length,close_calls:S.close_calls});});
test('T78','Restart with an outstanding order and zero positions','Do not unlock entry while an unreconciled order exists',()=>{S.orders.push({symbol:'XAUUSD',volume:0.5,sl:99,magic:560101});OnInit();S.gv.set('QDB1.EXEC.CERT',1);let sent=SendEntry(event());return outcome(!sent,{sent,recovery_lock:g_recovery_lock,orders:S.orders.length});});
test('T79','Missing bus payload key with matching SEQ','Reject incomplete payload even if SEQ and HEAD match',()=>{publish(event());S.gv.delete(QrosBusSlotKey(1,1,'SL'));let e=new QrosBusEvent();let read=QrosBusRead(1,1,e);return outcome(!read,{read,sl:e.sl});});
test('T80','Delayed modify is dropped after broker rejection','Retain desired protection until confirmed or escalated',()=>{position();let e=event();e.sl=99.5;S.modify={ok:false,rc:REJECT,apply:false};HandleModify(e);S.modify={ok:true,rc:TRADE_RETCODE_DONE,apply:true};OnTimer();return outcome(S.positions[0].sl===99.5,{sl:S.positions[0].sl,modify_calls:S.modify_calls});});

test('T81','New-day OnTick before forced close timer','No new entry before resolving prior-day exposure',()=>{position(1,{time:S.now-86400});publish(event(2));PollBus();S.uptime+=300;OnTick();return outcome(!S.requests.length,{requests:S.requests.length,prior_day_still_open:S.positions.some(p=>p.time<S.now-3600),close_calls:S.close_calls});});
test('T82','Runtime freshness after disconnect','Block send with disconnected terminal despite fresh module heartbeats',()=>{S.connected=false;let sent=SendEntry(event());return outcome(!sent,{sent,connected:false,scope:'Stub accepts request; real broker disconnect response remains external BLOCKED'});});
test('T83','Initial risk kernel BUY and SELL controls','Both sides size at or below 50 USD on synthetic linear symbol',()=>{let a=new QrosRiskResult(),b=new QrosRiskResult();let x=QrosRiskSize('XAUUSD',0,100,99,10000,0.5,a);let y=QrosRiskSize('XAUUSD',1,100,101,10000,0.5,b);return outcome(x&&y&&a.actual_risk_usd<=50&&b.actual_risk_usd<=50,{buy_risk:a.actual_risk_usd,sell_risk:b.actual_risk_usd});});
test('T84','Risk target property sweep','Volume stays on step and bounded in representative finite cases',()=>{let checked=0,violations=[];for(const step of [0.01,0.03,0.1,0.25])for(const balance of [100,1000,10000])for(const dist of [0.1,1,7]){S.spec.step=step;S.spec.min=step;let rr=new QrosRiskResult();let ok=QrosRiskSize('XAUUSD',0,100,100-dist,balance,0.5,rr);checked++;if(ok&&(rr.actual_risk_usd>balance*0.005+0.01||Math.abs(rr.volume/step-Math.round(rr.volume/step))>1e-8))violations.push({step,balance,dist});}return outcome(!violations.length,{checked,violations});});
test('T85','Ordinary close then new entry ordering','Confirmed earlier close frees visible asset before mature entry',()=>{position();publish(event(1,S.now*1000,0,3));publish(event(1,S.now*1000+1));PollBus();S.uptime+=300;ProcessPending();return outcome(S.close_calls===1&&S.requests.length===1&&S.positions.length===1,{close_calls:S.close_calls,requests:S.requests.length,positions:S.positions.length});});
test('T86','Double sequence commit changes during read','Reject changed commit in final recheck',()=>{publish(event());let fired=false;S.onGet=k=>{if(!fired&&k===QrosBusSlotKey(1,1,'SL')){fired=true;S.gv.set(QrosBusSlotKey(1,1,'SEQ'),33);}};let e=new QrosBusEvent();let read=QrosBusRead(1,1,e);return outcome(!read,{read,commit:S.gv.get(QrosBusSlotKey(1,1,'SEQ'))});});
test('T87','Continuous faults stop every later timer','Every declared runtime fault reason leaves day-boundary fallback available',()=>{const reasons=['BUS_OVERFLOW_MODULE_1','BUS_TORN_OR_MISSING_MODULE_1','RESERVED_RISK_UNKNOWN','MQL_TRADE_NOT_ALLOWED','TERMINAL_TRADE_NOT_ALLOWED','INVALID_ARM_TOKEN','ACCOUNT_NOT_DEMO','WRONG_SERVER_x','WRONG_CURRENCY_x','FROZEN_RISK_OR_CAP_MISMATCH'];let results=[];for(const reason of reasons){reset();position(1,{time:S.now-86400});SetFault(reason);OnTimer();results.push({reason,remaining:S.positions.length,close_calls:S.close_calls});}return outcome(results.every(x=>x.remaining===0),{results,scope:'Reasons injected after init with authorized demo arm state restored; not a claim that all are naturally reachable during forward'});});
process.stdout.write(JSON.stringify(RESULTS,null,2)+'\n');


