// QROS Mobile G12 TEST_ONLY. Renewable session + resumable synthetic jobs.
export const encoder=new TextEncoder();
export function canonical(v){if(v===null||typeof v==='boolean'||typeof v==='string')return JSON.stringify(v);if(typeof v==='number'&&Number.isSafeInteger(v))return String(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(v&&Object.getPrototypeOf(v)===Object.prototype)return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';throw Error('invalid_canonical_type');}
export async function sha(d){const b=typeof d==='string'?encoder.encode(d):d;const x=new Uint8Array(await crypto.subtle.digest('SHA-256',b));return Array.from(x,n=>n.toString(16).padStart(2,'0')).join('');}
export function token(n=32){const b=crypto.getRandomValues(new Uint8Array(n));let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/g,'');}
export function response(status,data){return new Response(canonical(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store, max-age=0','Pragma':'no-cache','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'"}});}
export function exactObject(o,k){return !!o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).sort().join(',')===[...k].sort().join(',');}
export async function jsonBody(req,k,max=8192){if((req.headers.get('Content-Type')||'').split(';')[0].trim()!=='application/json')throw Error('content_type');const raw=await req.text();if(!raw||raw.length>max)throw Error('body_size');const d=JSON.parse(raw);if(!exactObject(d,k))throw Error('body_schema');return d;}
export function validOrigin(req,env){const u=new URL(req.url);return u.protocol==='https:'&&u.origin===env.PUBLIC_ORIGIN&&!u.search&&!u.hash&&!req.headers.has('Origin');}
export function validOpaque(v,min=43,max=128){return typeof v==='string'&&v.length>=min&&v.length<=max&&/^[A-Za-z0-9_-]+$/.test(v);}
export function validId(v,max=96){return typeof v==='string'&&v.length>=1&&v.length<=max&&/^[A-Za-z0-9][A-Za-z0-9_.:-]*$/.test(v);}
export function pairingGrantRegistry(env,now){const a=JSON.parse(env.PAIRING_GRANTS_JSON);if(!Array.isArray(a)||a.length<1||a.length>100)throw Error('pair_registry');for(const g of a){if(!exactObject(g,['pairing_sha256','tenant','client','nbf','exp'])||!/^[0-9a-f]{64}$/.test(g.pairing_sha256)||!validId(g.tenant)||!validId(g.client)||!Number.isSafeInteger(g.nbf)||!Number.isSafeInteger(g.exp)||g.exp<=g.nbf||g.exp-g.nbf>604800)throw Error('pair_registry');}return a.filter(g=>g.nbf<=now&&now<g.exp);}
export function bearer(req){const h=req.headers.get('Authorization')||'';if(!h.startsWith('Bearer '))return null;const t=h.slice(7);return validOpaque(t)?t:null;}
export const publicSession=b=>({schema:'QROS_G12_SESSION_V1',mode:'TEST_ONLY_SYNTHETIC',scientific_authority:'NONE',access_token:b.accessToken,refresh_token:b.refreshToken,access_exp:b.accessExp,refresh_exp:b.refreshExp,tenant:b.tenant,client:b.client});
export const publicJob=j=>({schema:'QROS_G12_SYNTHETIC_JOB_V1',mode:'TEST_ONLY_SYNTHETIC',scientific_authority:'NONE',job_id:j.id,state:j.state,cursor:j.cursor,total_units:j.totalUnits,search_space_sha256:j.searchSpaceSha256,toy_enumeration_sha256:j.toyEnumerationSha256,result_sha256:j.resultSha256??null,economic_backtests:0,holdout_open:false,ga2_open:false,mt5_executed:false});
