import {DurableObject} from 'cloudflare:workers';
import {bearer,canonical,exactObject,jsonBody,pairingGrantRegistry,publicJob,publicSession,response,sha,token,validId,validOpaque,validOrigin} from './core.mjs';
const ACCESS_TTL=900,REFRESH_TTL=604800,JOB_CHUNK=256,MAX_JOB_UNITS=10000;
export class AuthState extends DurableObject{
 async _bundle(client,tenant,now){const accessToken=token(32),refreshToken=token(48);return{client,tenant,accessToken,refreshToken,accessHash:await sha(accessToken),refreshHash:await sha(refreshToken),accessExp:now+ACCESS_TTL,refreshExp:now+REFRESH_TTL};}
 async issue(ph,client,tenant,now){const b=await this._bundle(client,tenant,now);return this.ctx.storage.transaction(async tx=>{if(await tx.get('pair:'+ph))return{status:409};await tx.put('pair:'+ph,{used:now,client,tenant});await tx.put('access:'+b.accessHash,{client,tenant,exp:b.accessExp,refreshHash:b.refreshHash});await tx.put('refresh:'+b.refreshHash,{client,tenant,exp:b.refreshExp,accessHash:b.accessHash});return{status:200,bundle:b};});}
 async authorize(ah,now){const r=await this.ctx.storage.get('access:'+ah);return!r||r.exp<=now?null:{client:r.client,tenant:r.tenant};}
 async refresh(rh,now){const old=await this.ctx.storage.get('refresh:'+rh);if(!old||old.exp<=now)return{status:401};const b=await this._bundle(old.client,old.tenant,now);return this.ctx.storage.transaction(async tx=>{const current=await tx.get('refresh:'+rh);if(!current||current.exp<=now)return{status:401};await tx.delete('refresh:'+rh);await tx.delete('access:'+current.accessHash);await tx.put('access:'+b.accessHash,{client:b.client,tenant:b.tenant,exp:b.accessExp,refreshHash:b.refreshHash});await tx.put('refresh:'+b.refreshHash,{client:b.client,tenant:b.tenant,exp:b.refreshExp,accessHash:b.accessHash});return{status:200,bundle:b};});}
 async revoke(rh){return this.ctx.storage.transaction(async tx=>{const old=await tx.get('refresh:'+rh);if(old){await tx.delete('access:'+old.accessHash);await tx.delete('refresh:'+rh);}return 204;});}
}
export class JobState extends DurableObject{
 async create(who,spec,idem,now){return this.ctx.storage.transaction(async tx=>{const ik='idem:'+who.tenant+':'+who.client+':'+idem,existing=await tx.get(ik);if(existing)return{created:false,job:await tx.get('job:'+existing)};const id='job_'+token(18),job={id,tenant:who.tenant,client:who.client,createdAt:now,state:'RUNNING',cursor:0,totalUnits:spec.total_units,searchSpaceSha256:spec.search_space_sha256,toyEnumerationSha256:spec.toy_enumeration_sha256,resultSha256:null};await tx.put('job:'+id,job);await tx.put(ik,id);return{created:true,job};});}
 async advance(who,id){return this.ctx.storage.transaction(async tx=>{const key='job:'+id,job=await tx.get(key);if(!job)return{status:404};if(job.client!==who.client||job.tenant!==who.tenant)return{status:403};if(job.state!=='COMPLETED'){job.cursor=Math.min(job.totalUnits,job.cursor+JOB_CHUNK);if(job.cursor===job.totalUnits){job.state='COMPLETED';job.resultSha256=await sha(canonical({schema:'QROS_G12_SYNTHETIC_RESULT_V1',search_space_sha256:job.searchSpaceSha256,toy_enumeration_sha256:job.toyEnumerationSha256,total_units:job.totalUnits,classification:'TEST_ONLY_SYNTHETIC'}));}await tx.put(key,job);}return{status:200,job};});}
}
const auth=env=>env.AUTH_STATE.get(env.AUTH_STATE.idFromName('g12-auth-v1')),jobs=env=>env.JOB_STATE.get(env.JOB_STATE.idFromName('g12-jobs-v1'));
async function identity(req,env,now){const t=bearer(req);return t?auth(env).authorize(await sha(t),now):null;}
function safeJob(b){if(!exactObject(b,['search_space_sha256','toy_enumeration_sha256','total_units','idempotency_key']))return null;if(!/^[0-9a-f]{64}$/.test(b.search_space_sha256)||!/^[0-9a-f]{64}$/.test(b.toy_enumeration_sha256)||!Number.isSafeInteger(b.total_units)||b.total_units<1||b.total_units>MAX_JOB_UNITS||!validOpaque(b.idempotency_key,16,80))return null;return b;}
export async function handle(req,env,now=Math.floor(Date.now()/1000)){try{if(env.ENABLED!=='true')return response(503,{error:'unavailable'});if(!validOrigin(req,env))return response(403,{error:'request_denied'});const u=new URL(req.url);
if(req.method==='POST'&&u.pathname==='/v1/session/exchange'){const b=await jsonBody(req,['pairing_code','client_id']);if(!validOpaque(b.pairing_code,43,128)||!validId(b.client_id))return response(400,{error:'invalid_request'});const ph=await sha(b.pairing_code),g=pairingGrantRegistry(env,now).filter(x=>x.pairing_sha256===ph&&x.client===b.client_id);if(g.length!==1)return response(401,{error:'pairing_denied'});const r=await auth(env).issue(ph,g[0].client,g[0].tenant,now);return r.status===200?response(200,publicSession(r.bundle)):response(r.status,{error:'pairing_denied'});}
if(req.method==='POST'&&u.pathname==='/v1/session/refresh'){const b=await jsonBody(req,['refresh_token']);if(!validOpaque(b.refresh_token))return response(400,{error:'invalid_request'});const r=await auth(env).refresh(await sha(b.refresh_token),now);return r.status===200?response(200,publicSession(r.bundle)):response(401,{error:'session_expired'});}
if(req.method==='POST'&&u.pathname==='/v1/session/revoke'){const b=await jsonBody(req,['refresh_token']);if(!validOpaque(b.refresh_token))return response(400,{error:'invalid_request'});await auth(env).revoke(await sha(b.refresh_token));return new Response(null,{status:204,headers:{'Cache-Control':'no-store'}});}
if(req.method==='POST'&&u.pathname==='/v1/jobs'){const who=await identity(req,env,now);if(!who)return response(401,{error:'session_expired'});const b=safeJob(await jsonBody(req,['search_space_sha256','toy_enumeration_sha256','total_units','idempotency_key']));if(!b)return response(400,{error:'invalid_job'});const m=await jobs(env).create(who,b,b.idempotency_key,now);return response(m.created?202:200,publicJob(m.job));}
const m=/^\/v1\/jobs\/(job_[A-Za-z0-9_-]{20,80})$/.exec(u.pathname);if(req.method==='GET'&&m){const who=await identity(req,env,now);if(!who)return response(401,{error:'session_expired'});const r=await jobs(env).advance(who,m[1]);return r.status===200?response(200,publicJob(r.job)):response(r.status,{error:'job_denied'});}return response(404,{error:'not_found'});}catch{return response(503,{error:'unavailable'});}}
export default{fetch:handle};
